name: pt_platform

description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.4+17

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  add_2_calendar: 2.2.4
  awesome_circular_chart: ^1.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  dropdown_search:
    path: dropdown_search-5.0.6
  equatable: ^2.0.5
  fijkplayer: ^0.11.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_database: ^10.3.6
  firebase_dynamic_links: ^5.4.12
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_plugin_android_lifecycle: ^2.0.16
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.8
  flutter_widget_from_html: ^0.14.6
  fluttertoast: ^8.2.2
  get: ^4.6.6
  get_it: ^7.6.4
  get_storage: ^2.1.1
  html: ^0.15.4
  http: ^1.2.0
  image_picker: ^1.0.4
  in_app_purchase: ^3.1.13
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  intl_phone_field:
    path: intl_phone_field-3.2.0
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  onesignal_flutter: ^5.0.3
  open_file: ^3.3.2
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  permission_handler: 11.0.0
  photo_view: ^0.14.0
  pinput: ^3.0.1
  pull_to_refresh: ^2.0.0
  redacted: ^1.0.11
  share_plus: ^7.2.2
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  webview_flutter: ^4.5.0
  wheel_chooser: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.4.4
  rename: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pt_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# flutter pub run flutter_launcher_icons pubspec.yaml
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/coach_image/
    - assets/
