name: pt_platform

description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  permission_handler: 11.0.0
  intl: ^0.18.0
  lottie: ^2.6.0
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  flutter_plugin_android_lifecycle: ^2.0.16
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  pinput: ^3.0.1
  flutter_localization: ^0.1.14
  carousel_slider: ^4.2.1
  awesome_circular_chart: ^1.0.0
  wheel_chooser: ^1.1.2
  video_player: ^2.7.2
  chewie: ^1.7.1
  package_info_plus: ^4.2.0
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.2
  photo_view: ^0.14.0
  http: ^1.1.0
  flutter_calendar_carousel: ^2.4.2
  intl_phone_field:
    path: intl_phone_field-3.2.0
  dropdown_search:
    path: dropdown_search-5.0.6
  timezone: ^0.9.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  redacted: ^1.0.11
  webview_flutter: ^4.4.2
  flutter_widget_from_html: ^0.14.6
#  firebase_core: ^2.24.0
  firebase_database: ^10.3.6
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  pull_to_refresh: ^2.0.0
  add_2_calendar: ^2.2.5
  onesignal_flutter: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  rename: ^3.0.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/pt_icon.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

# flutter pub run flutter_launcher_icons pubspec.yaml


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/coach_image/
