// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGPbLU4RWC1TjT0EzeRLF2EWlr3fbvnE',
    appId: '1:1065042722156:android:862ff20c5c491041d54749',
    messagingSenderId: '1065042722156',
    projectId: 'pt-platform-686d1',
    databaseURL:
        'https://pt-platform-686d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pt-platform-686d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtXk4FBFzvPg1D7QnxX8AXX-ALdPb76M',
    appId: '1:1065042722156:ios:907ed6404585c01ed54749',
    messagingSenderId: '1065042722156',
    projectId: 'pt-platform-686d1',
    databaseURL:
        'https://pt-platform-686d1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pt-platform-686d1.appspot.com',
    iosBundleId: 'com.smartedge.ptapp',
  );
}
